name: Codium PR Agent

on:
  workflow_call:
    inputs:
      before_step_command:
        description: "Command to execute at the start of the job"
        type: string
        default: ""
      after_step_command:
        description: "Command to execute at the end of the job"
        type: string
        default: ""

jobs:
  pr_agent:
    name: pr_agent
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: read
    steps:
      - name: before step
        if: ${{ inputs.before_step_command != '' }}
        run: |
          ${{ inputs.before_step_command}}
      - name: PR Agent Scan
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: after step
        if: ${{ inputs.after_step_command != '' }}
        run: |
          ${{ inputs.after_step_command}}
