name: Git Release
on:
  push:
    branches:
      - master
      - main
      - hotfix/**

jobs:
  call_workflow:
    uses: ./.github/workflows/release-please.yml
    secrets: inherit
    with:
      RELEASE_TYPE: "simple"
